FROM php:7.2-apache 

RUN apt update -y && apt upgrade -y
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt install openssl

COPY Config/www.mes-b1.ephec-ti.be.conf /etc/apache2/sites-available
COPY Config/b2b.mes-b1.ephec-ti.be.conf /etc/apache2/sites-available

RUN ln -s /etc/apache2/sites-available/www.mes-b1.ephec-ti.be.conf /etc/apache2/sites-enabled
RUN ln -s /etc/apache2/sites-available/b2b.mes-b1.ephec-ti.be.conf /etc/apache2/sites-enabled

RUN mkdir /var/www/www.mes-b1.ephec-ti.be
RUN mkdir /var/www/b2b.mes-b1.ephec-ti.be

COPY /Code_Sites/www/index.html /var/www/www.mes-b1.ephec-ti.be
COPY /Code_Sites/b2b/index.php /var/www/b2b.mes-b1.ephec-ti.be

COPY /Certificats/cert.pem /etc/ssl/certs/cert.pem
COPY /Certificats/cert-key.pem /etc/ssl/certs/cert-key.pem

RUN a2enmod ssl          
RUN service apache2 start